@{
    CatalogAdditionIds = @(32, 37, 58, 60, 167)

    # Runtime-facing labels for exercises whose lineage cannot be recovered
    # reliably from the display name alone.
    CatalogPracticeOverrides = @{
        31 = 'Tai Chi'
        32 = 'Gait retraining'
        37 = 'Low-impact aerobics'
        58 = 'Bhangra'
        60 = 'Low-impact aerobics'
        108 = 'Ballet'
        167 = 'Running drills'
        187 = 'Ballet'
        188 = 'Ballet'
        197 = 'Ballet'
        198 = 'Ballet'
        389 = 'Ballet'
        394 = 'Breathwork'
        395 = 'Breathwork'
        397 = 'Breathwork'
        398 = 'Breathwork'
        399 = 'Qigong'
        400 = 'Qigong'
        401 = 'Qigong'
        402 = 'Qigong'
        403 = 'Qigong'
        404 = 'Qigong'
        405 = 'Qigong'
        406 = 'Qigong'
        409 = 'Functional Range Conditioning'
        467 = 'Qigong'
        475 = 'Jazz dance'
        501 = 'Vestibular rehabilitation'
        502 = 'Vestibular rehabilitation'
        503 = 'Vestibular rehabilitation'
        504 = 'Vestibular rehabilitation'
        626 = 'Sumo'
        960 = 'Fundamental movement skills'
        969 = 'Yoga'
    }

    # Default catalog-label to DAG-node mapping. Broad nodes are intentional
    # where the legacy label does not preserve a defensible specific lineage.
    DagMappings = @{
        'Acting facial-expression control' = @('mime')
        'Active isolated stretching' = @('fitness')
        'Active neck mobility' = @('fitness')
        'Balance training' = @('fitness')
        'Balance and gaze-control mobility' = @('vestibular_rehabilitation')
        'Balance and neck mobility' = @('vestibular_rehabilitation')
        'Balance and vestibular training' = @('vestibular_rehabilitation')
        'Ballet' = @('ballet')
        'Ballet conditioning' = @('ballet')
        'Backward walking' = @('backward_walking')
        'Belly dance' = @('belly_dance_raqs_sharqi')
        'Bhangra' = @('bhangra')
        'Bharatanatyam' = @('bharatanatyam')
        'Bodybuilding posing' = @('bodybuilding')
        'Bodyweight cardio boxing' = @('boxing', 'fitness_endurance')
        'Bodyweight cardio conditioning' = @('fitness_endurance')
        'Bodyweight conditioning' = @('calisthenics')
        'Bodyweight isometrics' = @('calisthenics')
        'Bodyweight strength' = @('calisthenics')
        'Bodyweight upper-body warm-up' = @('calisthenics')
        'Boxing' = @('boxing')
        'Boxing and cardio conditioning' = @('boxing', 'fitness_endurance')
        'Boxing and plyometric conditioning' = @('boxing', 'fitness_endurance')
        'Boxing cardio conditioning' = @('boxing', 'fitness_endurance')
        'Boxing conditioning' = @('boxing')
        'Brain-calibration training' = @('neuromotor_rehabilitation')
        'Breath-led conditioning' = @('breathwork_mobility_flows')
        'Breath-led mobility' = @('breathwork_mobility_flows')
        'Breath-led yoga' = @('somatics_yoga')
        'Breathwork' = @('somatics_breath')
        'Calf and ankle strengthening' = @('fitness_resistance')
        'Calf isometrics' = @('fitness_resistance')
        'Calf strengthening' = @('fitness_resistance')
        'Calisthenics' = @('calisthenics')
        'Cardio and bodyweight conditioning' = @('fitness_endurance', 'calisthenics')
        'Cardio conditioning' = @('fitness_endurance')
        'Cardio coordination' = @('fitness_endurance')
        'Capoeira' = @('capoeira')
        'Chest and shoulder mobility' = @('fitness')
        'Clinical stretching' = @('healing_rehab')
        'Deep-squat locomotion' = @('fitness')
        'Deep-squat mobility' = @('fitness')
        'Dynamic balance training' = @('fitness')
        'Dynamic leg mobility' = @('fitness')
        'Eight Nests qigong' = @('qigong')
        'Facial action isolation' = @('mime')
        'Facial movement exercise' = @('neuromotor_rehabilitation')
        'Foot and ankle strengthening' = @('fitness_resistance')
        'Forearm mobility' = @('fitness')
        'Functional Range Conditioning' = @('functional_range_conditioning')
        'Fundamental movement skills' = @('fundamental_movement_skills')
        'Gait retraining' = @('gait_retraining')
        'Hand and forearm mobility' = @('healing_rehab')
        'Hand conditioning' = @('fitness_resistance')
        'Hand coordination' = @('neuromotor_rehabilitation')
        'Hand mobility' = @('healing_rehab')
        'Hand therapy' = @('healing_rehab')
        'Hand therapy tendon gliding' = @('healing_rehab')
        'Hand therapy and mobility' = @('healing_rehab')
        'Hip stability training' = @('fitness_resistance')
        'Hula' = @('hula')
        'Jazz dance' = @('jazz_dance')
        'Jaw mobility' = @('healing_rehab')
        'Karate' = @('karate')
        'Karate conditioning' = @('karate')
        'Laughter yoga' = @('somatics_yoga')
        'Low-impact aerobics' = @('aerobics')
        'Low-impact boxing conditioning' = @('boxing', 'fitness_endurance')
        'Low-impact conditioning' = @('fitness_endurance')
        'Martial-arts conditioning' = @('fitness_endurance')
        'Muay Thai' = @('muay_thai')
        'Ninja hand-seal coordination' = @()
        'Odissi' = @('odissi')
        'Oculomotor rehabilitation' = @('vestibular_rehabilitation')
        'Pilates' = @('somatics_pilates')
        'Plyometric balance conditioning' = @('fitness_endurance')
        'Plyometric conditioning' = @('fitness_endurance')
        'Plyometric landing mechanics' = @('fitness_endurance')
        'Plyometric posterior-chain conditioning' = @('fitness_endurance')
        'Popping and waving' = @('popping')
        'Qigong' = @('qigong')
        'Qigong body tapping' = @('qigong')
        'Qigong shoulder mobility' = @('qigong')
        'Rope-free cardio conditioning' = @('fitness_endurance')
        'Running drills' = @('running')
        'Samba' = @('samba')
        'Self-resistance' = @('fitness_resistance')
        'Shoulder endurance' = @('fitness_resistance')
        'Shoulder isometrics' = @('fitness_resistance')
        'Shoulder mobility' = @('fitness')
        'Shoulder mobility and conditioning' = @('fitness')
        'Shoulder rehabilitation' = @('healing_rehab')
        'Single-leg balance training' = @('fitness')
        'Speech articulation practice' = @('vocal_breath_movement_work')
        'Standing ankle strengthening' = @('fitness_resistance')
        'Standing balance' = @('fitness')
        'Standing balance and mobility' = @('fitness')
        'Standing balance training' = @('fitness')
        'Standing bodyweight conditioning' = @('calisthenics')
        'Standing conditioning' = @('fitness')
        'Standing core conditioning' = @('calisthenics')
        'Standing hand and wrist stretching' = @('fitness')
        'Standing isometrics' = @('fitness_resistance')
        'Standing lower-body conditioning' = @('calisthenics')
        'Standing mobility' = @('fitness')
        'Standing mobility and movement practice' = @('fitness')
        'Standing mobility and stretching' = @('fitness')
        'Standing pelvic mobility' = @('fitness')
        'Standing pelvic-floor movement' = @('fitness')
        'Standing Pilates' = @('somatics_pilates')
        'Standing posterior-chain conditioning' = @('calisthenics')
        'Standing shoulder mobility' = @('fitness')
        'Standing strength and balance' = @('calisthenics')
        'Standing strength and mobility' = @('calisthenics')
        'Standing stretching' = @('fitness')
        'Standing upper-back conditioning' = @('calisthenics')
        'Standing upper-body conditioning' = @('calisthenics')
        'Standing yoga' = @('somatics_yoga')
        'Stretching' = @('fitness')
        'Sumo' = @('sumo')
        'Taiji Qigong Shibashi' = @('qigong')
        'Taekwondo' = @('taekwondo')
        'Tai Chi' = @('taijiquan')
        'Tutting' = @('hip_hop_freestyle')
        'Upper-back isometrics' = @('fitness_resistance')
        'Upper-body warm-up' = @('fitness')
        'Vestibular and neck conditioning' = @('vestibular_rehabilitation')
        'Vestibular and visual-motor conditioning' = @('vestibular_rehabilitation')
        'Vestibular rehabilitation' = @('vestibular_rehabilitation')
        'Wing Chun' = @('wing_chun')
        'Wrist mobility' = @('healing_rehab')
        'Wrist stretching' = @('fitness')
        'Yoga' = @('somatics_yoga')
        'Yoga breathing' = @('somatics_yoga')
    }
}
