@{
    FEET = @(
        'Ankle Dorsiflexion Rock'
        'Ankle Plantarflexion Point'
        'Ankle Inversion Sweep'
        'Ankle Eversion Sweep'
        'Ankle Alphabet'
        'Ankle Circle'
        'Ankle Controlled Articular Rotation'
        'Standing Double Heel Raise'
        'Standing Single-Leg Heel Raise'
        'Standing Bent-Knee Heel Raise'
        'Standing Forefoot Lift'
        'Heel-to-Toe Rock'
        'Lateral Foot Rock'
        'Tripod Foot Press'
        'Single-Leg Balance'
        'Tandem Stance'
        'Semi-Tandem Stance'
        'Narrow-Stance Balance'
        'Staggered-Stance Balance'
        'Flamingo Balance'
        'Airplane Balance'
        'Star Excursion Balance'
        'Y-Balance Reach'
        'Clock-Reach Balance'
        'Compass-Reach Balance'
        'Single-Leg Pendulum'
        'Single-Leg Figure-Eight Reach'
        'Single-Leg Around-the-World Reach'
        'Heel Walk'
        'Forefoot Walk'
        'Tandem Walk'
        'Tightrope Walk'
        'Box Step'
        'V-Step'
        'A-Step'
        'Step Touch'
        'Side Step-and-Close'
        'Crossover Step'
        'Cross-Behind Step'
        'Forward Step-and-Close'
        'Backward Step-and-Close'
        'Diagonal Step-and-Close'
        'Three-Step Turn'
        'Pivot Turn'
        'Quarter-Turn Step'
        'Half-Turn Step'
        'Clock Step'
        'Square Step'
        'Diamond Step'
        'Triangle Step'
        'L-Step'
        'T-Step'
        'Charleston Step'
        'Jazz Square'
        'Pas de Bourree'
        'Grapevine Step'
        'Carioca Step'
        'Two-Step'
        'Foxtrot Box Step'
        'Waltz Box Step'
        'Rumba Box Step'
        'Cha-Cha Basic Step'
        'Salsa Basic Step'
        'Bachata Basic Step'
        'Merengue Basic Step'
        'Mambo Basic Step'
        'Samba Whisk'
        'Tai Chi Empty Step'
        'Tai Chi Bow Step'
        'Tai Chi Cat Step'
        'Tai Chi T-Step'
        'Tai Chi Heel Step'
        'Tai Chi Toe Step'
        'Tai Chi Brush Step'
        'Tai Chi Cloud Step'
        'Tai Chi Repulse Step'
        'Bagua Mud Step'
        'Bagua Circle Walk'
        'Bagua Kou Bu'
        'Bagua Bai Bu'
        'Xingyi Chicken Step'
        'Karate Suri-Ashi'
        'Karate Yori-Ashi'
        'Karate Ayumi-Ashi'
        'Karate Tsugi-Ashi'
        'Fencing Advance'
        'Fencing Retreat'
        'Boxing Step-and-Slide'
        'Boxing L-Step'
        'Boxing Pivot'
        'Boxing Circle Step'
        'Capoeira Ginga'
        'Capoeira Esquiva Lateral'
        'Kalaripayattu Horse Step'
        'Controlled March'
        'Side-to-Side Weight Shift'
        'Forward-and-Back Weight Shift'
        'Diagonal Weight Shift'
        'Figure-Eight Weight Shift'
        'Four-Corner Weight Shift'
    )
    LEGS = @(
        'Bodyweight Squat'
        'Narrow-Stance Squat'
        'Wide-Stance Squat'
        'Sumo Squat'
        'Plie Squat'
        'Quarter Squat'
        'Half Squat'
        'Deep Squat'
        'Split Squat'
        'Staggered-Stance Squat'
        'Kickstand Squat'
        'Prisoner Squat'
        'Bodyweight Overhead Squat'
        'Hindu Squat'
        'Sissy Squat'
        'Cossack Squat'
        'Lateral Squat'
        'Squat to Knee Drive'
        'Squat to Calf Raise'
        'Duck Walk'
        'Forward Lunge'
        'Reverse Lunge'
        'Lateral Lunge'
        'Curtsy Lunge'
        'Diagonal Lunge'
        'Clock Lunge'
        'Walking Lunge'
        'Alternating Lunge'
        'Static Lunge'
        'Crescent Lunge'
        'High Lunge'
        'Warrior I Pose'
        'Warrior II Pose'
        'Reverse Warrior Pose'
        'Extended Side Angle Pose'
        'Goddess Pose'
        'Chair Pose'
        'Eagle Pose'
        'Tree Pose'
        'Dancer Pose'
        'Warrior III Pose'
        'Half Moon Pose'
        'Standing Hand-to-Big-Toe Pose'
        'Standing Knee Lift'
        'Standing Knee Extension'
        'Standing Hamstring Curl'
        'Standing Hip Flexion'
        'Standing Hip Extension'
        'Standing Hip Abduction'
        'Standing Hip Adduction'
        'Straight-Leg Front Raise'
        'Straight-Leg Side Raise'
        'Straight-Leg Back Raise'
        'Diagonal Leg Raise'
        'Front-to-Back Leg Swing'
        'Side-to-Side Leg Swing'
        'Knee Circle'
        'Open-the-Gate Knee Lift'
        'Standing Fire Hydrant'
        'Standing Donkey Kick'
        'Standing Gate Opener'
        'Double-Leg Calf Raise'
        'Bent-Knee Calf Raise'
        'Single-Leg Calf Raise'
        'Standing Tibialis Raise'
        'March in Place'
        'High-Knee March'
        'Toy Soldier March'
        'Standing Knee Drive'
        'Cross-Body Knee Drive'
        'Hamstring Sweep'
        'Heel Flick'
        'Side Knee Lift'
        'Front Kick'
        'Side Kick'
        'Back Kick'
        'Roundhouse Kick Chamber'
        'Crescent Kick'
        'Axe-Kick Leg Raise'
        'Karate Front Snap Kick'
        'Karate Side Thrust Kick'
        'Taekwondo Front-Kick Chamber'
        'Taekwondo Side-Kick Chamber'
        'Tai Chi Heel Kick'
        'Tai Chi Toe Kick'
        'Tai Chi Lotus Kick'
        'Tai Chi Golden Rooster Stance'
        'Qigong Crane Stance'
        'Ballet Demi-Plie'
        'Ballet Grand Plie'
        'Ballet Tendu Devant'
        'Ballet Tendu a la Seconde'
        'Ballet Tendu Derriere'
        'Ballet Degage Devant'
        'Ballet Degage a la Seconde'
        'Ballet Degage Derriere'
        'Ballet Fondu'
        'Ballet Passe Balance'
        'Ballet Retire Balance'
        'Ballet Attitude Balance'
    )
    HANDS = @(
        'Hand Open and Close'
        'Hook Fist'
        'Straight Fist'
        'Full Fist'
        'Tabletop Fist'
        'Tendon-Glide Sequence'
        'Finger Fan'
        'Finger Adduction'
        'Finger Abduction'
        'Thumb Opposition'
        'Thumb Palmar Abduction'
        'Thumb Radial Abduction'
        'Thumb Flexion'
        'Thumb Extension'
        'Thumb Circumduction'
        'Finger Wave'
        'Air Finger Walk'
        'Sequential Finger Lift'
        'Independent Finger Flexion'
        'Independent Finger Extension'
        'Finger-to-Thumb Taps'
        'Reverse Finger-to-Thumb Taps'
        'Air Piano'
        'Finger Scissors'
        'Finger Cross and Uncross'
        'Finger Hook and Release'
        'Finger Curl Cascade'
        'Finger Extension Cascade'
        'Finger Flick'
        'Quiet Hand Shakeout'
        'Wrist Flexion'
        'Wrist Extension'
        'Wrist Radial Deviation'
        'Wrist Ulnar Deviation'
        'Wrist Circle'
        'Wrist Figure Eight'
        'Forearm Pronation and Supination'
        'Prayer-Hand Stretch'
        'Reverse-Prayer Stretch'
        'Palm Press'
        'Fingertip Press'
        'Finger Pull-Apart Isometric'
        'Hook-Fist Isometric'
        'Fist-Squeeze Isometric'
        'Palm Cup and Flatten'
        'Hand Wave'
        'Palm Turnover'
        'Jazz Hands'
        'Claw Hand to Open Palm'
        'Crane-Beak Hand'
        'Tiger-Claw Hand'
        'Leopard-Fist Formation'
        'Spear-Hand Formation'
        'Knife-Hand Formation'
        'Ridge-Hand Formation'
        'Back-Fist Rotation'
        'Phoenix-Eye Fist Formation'
        'Wing Chun Wu Sau'
        'Wing Chun Tan Sau'
        'Wing Chun Bong Sau'
        'Wing Chun Fook Sau'
        'Wing Chun Pak Sau'
        'Wing Chun Gum Sau'
        'Wing Chun Huen Sau'
        'Wing Chun Bil Sau'
        'Wing Chun Lap Sau'
        'Karate Shuto Formation'
        'Karate Nukite Formation'
        'Qigong Laogong Opening'
        'Qigong Ball-Holding Hands'
        'Anjali Mudra'
        'Chin Mudra'
        'Prana Mudra'
        'Apana Mudra'
        'Vayu Mudra'
        'Varuna Mudra'
        'Surya Mudra'
        'Prithvi Mudra'
        'Shuni Mudra'
        'Dhyana Mudra'
        'Hakini Mudra'
        'Shankh Mudra'
        'Lotus Mudra'
        'Garuda Mudra'
        'Ganesha Mudra'
        'Kali Mudra'
        'Ksepana Mudra'
        'Matangi Mudra'
        'Rudra Mudra'
        'Kubera Mudra'
        'Pushan Mudra'
        'Mushti Mudra'
        'Shunya Mudra'
        'Linga Mudra'
        'Yoni Mudra'
        'Uttarabodhi Mudra'
        'Vajrapradama Mudra'
        'Hridaya Mudra'
        'Bhairava Mudra'
        'Shivalinga Mudra'
    )
    ARMS = @(
        'Forward Arm Circles'
        'Backward Arm Circles'
        'Alternating Arm Circles'
        'Windmill Arms'
        'Cross-Body Arm Swings'
        'Overhead Arm Swings'
        'Front Arm Raise'
        'Lateral Arm Raise'
        'Scaption Raise'
        'Standing Rear-Delt Sweep'
        'Standing Arm Crossover'
        'Standing Overhead Elbow-Extension Flow'
        'Shoulder-Rotation Press Flow'
        'Supinated Elbow Curl'
        'Neutral-Grip Elbow Curl'
        'Pronated Elbow Curl'
        'Standing Triceps Extension'
        'Standing Triceps Kickback'
        'Elbow Flexion and Extension'
        'Arm Figure Eight'
        'Alternating Overhead Reach'
        'Double Overhead Reach'
        'Cross-Body Reach'
        'Diagonal Arm Reach'
        'Lateral Arm Reach'
        'Forward Punch Reach'
        'Standing Rowing Arm Sweep'
        'Hug-a-Tree Arm Circle'
        'Qigong Gathering Qi'
        'Qigong Push-and-Pull'
        'Boxing Jab'
        'Boxing Cross'
        'Lead Hook'
        'Rear Hook'
        'Lead Uppercut'
        'Rear Uppercut'
        'Shovel Hook'
        'Overhand Punch'
        'Long-Guard Extension'
        'Double Straight Punch'
        'Alternating Straight Punches'
        'Body Jab'
        'Body Cross'
        'Boxing Parry'
        'Boxing Catch'
        'High-Guard Raise'
        'Peekaboo Guard Roll'
        'Karate Age-Uke'
        'Karate Gedan-Barai'
        'Karate Soto-Uke'
        'Karate Uchi-Uke'
        'Karate Shuto-Uke'
        'Karate Morote-Uke'
        'Karate Juji-Uke'
        'Karate Nagashi-Uke'
        'Karate Osae-Uke'
        'Karate Chudan-Zuki'
        'Karate Oi-Zuki'
        'Karate Gyaku-Zuki'
        'Karate Tate-Zuki'
        'Karate Uraken-Uchi'
        'Karate Empi-Uchi'
        'Wing Chun Chain Punches'
        'Wing Chun Lap-Sau Cycle'
        'Wing Chun Pak-Sau Cycle'
        'Wing Chun Tan-Bong-Fook Cycle'
        'Tai Chi Wave Hands Like Clouds'
        'Tai Chi Brush Knee Hand Sweep'
        'Tai Chi Repulse Monkey Arms'
        'Tai Chi Part Wild Horses Mane'
        'Tai Chi White Crane Spreads Wings'
        'Tai Chi Strike to Ears with Both Fists'
        'Tai Chi Grasp Sparrows Tail'
        'Tai Chi Single Whip'
        'Tai Chi High Pat on Horse'
        'Tai Chi Turn and Chop with Fist'
        'Qigong Lifting the Sky'
        'Qigong Separating Heaven and Earth'
        'Qigong Drawing the Bow'
        'Qigong Pushing Mountains'
        'Qigong Pushing the Waves'
        'Qigong Flying Crane Arms'
        'Qigong Swimming Dragon Arms'
        'Qigong Cloud Hands'
        'Qigong Circling the Arms'
        'Qigong Carrying the Moon'
        'Ballet First Port de Bras'
        'Ballet Second Port de Bras'
        'Ballet Third Port de Bras'
        'Ballet Fourth Port de Bras'
        'Ballet Fifth Port de Bras'
        'Ballet Allonge Arms'
        'Ballet Arabesque Arms'
        'Standing Backstroke Arm Cycle'
        'Standing Freestyle Arm Cycle'
        'Standing Breaststroke Arm Sweep'
        'Standing Butterfly Arm Sweep'
        'Standing Kayak Arm Pattern'
        'Nordic-Ski Arm Swing'
        'Speed-Skater Arm Swing'
    )
    HEAD = @(
        'Cervical Flexion'
        'Cervical Extension'
        'Cervical Rotation'
        'Cervical Lateral Flexion'
        'Cervical Retraction'
        'Cervical Protraction'
        'Neck Half-Circle'
        'Neck Figure Eight'
        'Neck Controlled Articular Rotation'
        'Nose Alphabet'
        'Nose Circle'
        'Nose Square'
        'Nose Infinity Sign'
        'Ear-to-Shoulder Glide'
        'Chin-to-Collarbone Turn'
        'Diagonal Head Tilt'
        'Side-to-Side Head Translation'
        'Forward-and-Back Head Translation'
        'Occipital Nod'
        'Atlas Nod'
        'Cervical Rotation Isometric'
        'Cervical Flexion Isometric'
        'Cervical Extension Isometric'
        'Cervical Lateral-Flexion Isometric'
        'Chin-Tuck Isometric'
        'Neck Elongation Hold'
        'Horizontal Smooth Pursuit'
        'Vertical Smooth Pursuit'
        'Diagonal Smooth Pursuit'
        'Circular Smooth Pursuit'
        'Figure-Eight Smooth Pursuit'
        'Near-Far Focus Shift'
        'Thumb Convergence Tracking'
        'Horizontal Saccades'
        'Vertical Saccades'
        'Diagonal Saccades'
        'Clock-Face Saccades'
        'Square-Path Saccades'
        'Triangle-Path Saccades'
        'Infinity-Path Saccades'
        'Peripheral-Awareness Scan'
        'Near-Point Convergence'
        'Horizontal Gaze Stabilization'
        'Vertical Gaze Stabilization'
        'Diagonal Gaze Stabilization'
        'Horizontal VOR Cancellation'
        'Vertical VOR Cancellation'
        'Horizontal VOR x1'
        'Vertical VOR x1'
        'Diagonal VOR x1'
        'Horizontal VOR x2'
        'Vertical VOR x2'
        'Head-and-Eyes Same-Direction Turn'
        'Head-and-Eyes Opposite-Direction Turn'
        'Eyes-Lead Head Turn'
        'Head-Lead Eyes Turn'
        'Gaze Shift Between Thumbs'
        'Nasagra Drishti'
        'Bhrumadhya Drishti'
        'Hastagrahe Drishti'
        'Angusthamadhye Drishti'
        'Urdhva Drishti'
        'Nabi-Chakra Drishti'
        'Parsva Drishti'
        'Padayoragrai Drishti'
        'Infinity Gaze Tracing'
        'Eight-Brocades Wise Owl Gazes Backward'
        'Qigong Crane Looks Back'
        'Qigong Turtle Retracts Neck'
        'Qigong Turtle Extends Neck'
        'Qigong White Crane Nods'
        'Qigong Dragon Surveys the Sea'
        'Qigong Tiger Watches Prey'
        'Ballet Spotting Drill'
        'Jazz Head Isolation'
        'Dance Head Slide'
        'Dance Head Roll'
        'Dance Head Accent Front'
        'Dance Head Accent Side'
        'Dance Head Accent Diagonal'
        'Salsa Spotting Drill'
        'Cha-Cha Spotting Drill'
        'Pirouette Spotting Drill'
        'Ballroom Promenade Head Turn'
        'Tango Head Flick'
        'Flamenco Head Turn'
        'Bharatanatyam Sama Shiro'
        'Bharatanatyam Udvahita Shiro'
        'Bharatanatyam Adhomukha Shiro'
        'Bharatanatyam Alolita Shiro'
        'Bharatanatyam Dhuta Shiro'
        'Bharatanatyam Kampita Shiro'
        'Bharatanatyam Paravritta Shiro'
        'Bharatanatyam Utkshipta Shiro'
        'Bharatanatyam Parivahita Shiro'
        'Kathak Side Gaze'
        'Odissi Sundari Griva'
        'Bharatanatyam Sundari Griva'
        'Bharatanatyam Tiraschina Griva'
        'Bharatanatyam Parivartita Griva'
    )
    SHOULDERS = @(
        'Shoulder Flexion'
        'Shoulder Extension'
        'Shoulder Abduction'
        'Shoulder Adduction'
        'Shoulder Horizontal Abduction'
        'Shoulder Horizontal Adduction'
        'Shoulder Internal Rotation'
        'Shoulder External Rotation'
        'Shoulder Controlled Articular Rotation'
        'Scapular Elevation'
        'Scapular Depression'
        'Scapular Protraction'
        'Scapular Retraction'
        'Scapular Upward Rotation'
        'Scapular Downward Rotation'
        'Shoulder Shrug'
        'Forward Shoulder Roll'
        'Backward Shoulder Roll'
        'Alternating Shoulder Roll'
        'Scapular Clock'
        'Scapular Figure Eight'
        'Shoulder-Blade Squeeze'
        'Serratus Reach'
        'Standing W Raise'
        'Standing Y Raise'
        'Standing T Raise'
        'Standing I Raise'
        'Goalpost Rotation'
        'Cactus-Arm Rotation'
        'Standing W External Rotation'
        'Cuban Shoulder Rotation'
        'External Rotation at Side'
        'External Rotation at Ninety Degrees'
        'Internal Rotation at Ninety Degrees'
        'Shoulder Flexion Isometric'
        'Shoulder Extension Isometric'
        'Shoulder Abduction Isometric'
        'Shoulder Adduction Isometric'
        'Shoulder External-Rotation Isometric'
        'Shoulder Internal-Rotation Isometric'
        'Standing Snow Angel'
        'Standing Reverse Snow Angel'
        'Scaption Arm Arc'
        'Overhead Reach and Pull'
        'Shoulder Halo'
        'Elbow Circle'
        'Bent-Elbow Shoulder Circle'
        'Standing Shoulder Pendulum'
        'Cross-Body Shoulder Stretch'
        'Overhead Triceps-Shoulder Stretch'
        'Eagle Arms'
        'Cow-Face Arms'
        'Garudasana Arm Flow'
        'Gomukhasana Arm Flow'
        'Cactus-to-Goalpost Flow'
        'Prayer-to-Overhead Flow'
        'Reverse-Prayer Shoulder Stretch'
        'Hands-Behind-Back Shoulder Lift'
        'Standing Scapular Push'
        'Bear-Hug Shoulder Stretch'
        'Boxing Shoulder Roll'
        'Philly-Shell Shoulder Roll'
        'Peekaboo-Guard Shoulder Rhythm'
        'Jab Shoulder Protraction'
        'Cross Shoulder Rotation'
        'Hook Shoulder Rotation'
        'Uppercut Shoulder Drive'
        'Karate Age-Uke Shoulder Path'
        'Karate Soto-Uke Shoulder Path'
        'Wing Chun Bong-Sau Shoulder Cycle'
        'Wing Chun Tan-Sau Shoulder Cycle'
        'Tai Chi White-Crane Shoulder Open'
        'Tai Chi Single-Whip Shoulder Open'
        'Tai Chi Cloud-Hands Shoulder Flow'
        'Qigong Shoulder Shaking'
        'Qigong Crane-Wing Shoulder Lift'
        'Qigong Swimming-Dragon Shoulder Roll'
        'Eight Brocades Two Hands Hold the Heavens'
        'Eight Brocades Draw the Bow'
        'Eight Brocades Wise Owl Looks Back'
        'Ballet Epaulement Croise'
        'Ballet Epaulement Efface'
        'Ballet Epaulement Ecarte'
        'Ballet Shoulder Port de Bras'
        'Flamenco Shoulder Rotation'
        'Flamenco Shoulder Shimmy'
        'Belly-Dance Shoulder Shimmy'
        'Belly-Dance Alternating Shoulder Roll'
        'Egyptian-Dance Shoulder Accent'
        'Samba Shoulder Roll'
        'Bharatanatyam Natyarambhe Hold'
        'Odissi Chowka Shoulder Isolation'
        'Kathak Shoulder Turn'
        'Standing Freestyle Recovery Drill'
        'Standing Backstroke Shoulder Cycle'
        'Standing Breaststroke Shoulder Sweep'
        'Standing Butterfly Shoulder Recovery'
        'Nordic-Ski Shoulder Swing'
        'Standing Scapular-Plane Sweep'
        'Overhead Shoulder-CAR Flow'
    )
    HIPS = @(
        'Hip Flexion'
        'Hip Extension'
        'Hip Abduction'
        'Hip Adduction'
        'Hip Internal Rotation'
        'Hip External Rotation'
        'Hip Controlled Articular Rotation'
        'Hip Circle'
        'Anterior Pelvic Tilt'
        'Posterior Pelvic Tilt'
        'Lateral Pelvic Tilt'
        'Pelvic Circle'
        'Pelvic Clock'
        'Pelvic Figure Eight'
        'Side-to-Side Hip Shift'
        'Forward-and-Back Hip Shift'
        'Knee-Led Hip Circle'
        'Open-the-Gate Hip Circle'
        'Close-the-Gate Hip Circle'
        'Standing Hip Airplane'
        'Standing Figure-Four Stretch'
        'Standing Pigeon Pose'
        'Tree-Pose Hip Opening'
        'Eagle-Pose Hip Adduction'
        'Horse Stance'
        'Sumo Stance'
        'Malasana Hip Shift'
        'Warrior-II Hip Opening'
        'Triangle-Pose Hip Hinge'
        'Half-Moon Hip Stack'
        'Dancer-Pose Hip Extension'
        'Crescent-Lunge Hip-Flexor Stretch'
        'Standing Quadriceps Stretch'
        'Standing Hamstring Hinge'
        'Good Morning'
        'Single-Leg Romanian Deadlift'
        'Kickstand Hip Hinge'
        'Staggered-Stance Hip Hinge'
        'Lateral Hip Hinge'
        'Cossack Weight Shift'
        'Standing Adductor Rock'
        'Standing Groin Shift'
        'Lateral-Lunge Hip Shift'
        'Curtsy Hip Sweep'
        'Standing Glute Squeeze'
        'Standing Glute Kickback'
        'Standing Glute Press'
        'Standing Hip-Abduction Arc'
        'Standing Hip-Abduction Leg Lift'
        'Standing Hip-Adduction Leg Sweep'
        'Front Leg Swing'
        'Sagittal Leg Pendulum'
        'Lateral Leg Swing'
        'Diagonal Leg Swing'
        'Hip Internal-Rotation Sweep'
        'Hip External-Rotation Sweep'
        'Ballet Rond de Jambe a Terre'
        'Ballet Rond de Jambe en l Air'
        'Ballet Passe'
        'Ballet Retire'
        'Ballet Developpe Devant'
        'Ballet Developpe a la Seconde'
        'Ballet Developpe Derriere'
        'Ballet Attitude Devant'
        'Ballet Attitude Derriere'
        'Ballet Arabesque'
        'Ballet Penche'
        'Ballet Fouette Preparation'
        'Salsa Hip Action'
        'Cuban Motion'
        'Rumba Hip Action'
        'Cha-Cha Hip Action'
        'Mambo Hip Action'
        'Bachata Hip Sway'
        'Merengue Hip Action'
        'Samba Pelvic Tilt'
        'Belly-Dance Hip Drop'
        'Belly-Dance Hip Lift'
        'Belly-Dance Hip Slide'
        'Belly-Dance Hip Bump'
        'Belly-Dance Horizontal Figure Eight'
        'Belly-Dance Vertical Figure Eight'
        'Belly-Dance Umi'
        'Belly-Dance Maya'
        'Belly-Dance Taqsim'
        'Belly-Dance Hip Twist'
        'Belly-Dance Hip Shimmy'
        'Belly-Dance Pendulum Swing'
        'Belly-Dance Pelvic Tuck and Release'
        'Belly-Dance Pelvic Undulation'
        'Tai Chi Kua Opening'
        'Tai Chi Kua Closing'
        'Tai Chi Silk-Reeling Hip Circle'
        'Tai Chi Bow-Stance Hip Shift'
        'Tai Chi Empty-Stance Hip Sink'
        'Bagua Hip Coil'
        'Xingyi Hip Drive'
        'Capoeira Ginga Hip Sway'
        'Karate Hip Snap'
        'Boxing Hip Rotation'
    )
    CHEST = @(
        'Chest Lift'
        'Chest Drop'
        'Side-to-Side Chest Slide'
        'Chest Circle'
        'Chest Figure Eight'
        'Forward-and-Back Ribcage Isolation'
        'Side-to-Side Ribcage Isolation'
        'Ribcage Circle'
        'Ribcage Figure Eight'
        'Sternum Lift'
        'Sternum Drop'
        'Thoracic Expansion Hold'
        'Lateral Rib Expansion'
        'Posterior Rib Expansion'
        'Standing 360-Degree Rib Breathing'
        'Standing Box Breathing'
        'Standing Diaphragmatic Breathing'
        'Standing Costal Breathing'
        'Standing Three-Part Yogic Breath'
        'Standing Coherent Breathing'
        'Chest-Squeeze Isometric'
        'Prayer Press'
        'Palm-Squeeze Svend Press'
        'Palm-to-Palm Chest Press'
        'Fist-to-Fist Chest Press'
        'Forearm Chest Press'
        'Standing Chest Fly'
        'Standing Reverse Chest Fly'
        'Self-Resisted Standing Chest Press'
        'Standing Alternating Palm Press'
        'Alternating Chest Press'
        'Single-Arm Chest Press'
        'Split-Stance Chest Press'
        'Diagonal Chest Press'
        'Low-to-High Chest Fly'
        'High-to-Low Chest Fly'
        'Cross-Body Chest Fly'
        'Standing Chest Opener'
        'Clasped-Hand Chest Opener'
        'Cactus Chest Opener'
        'Goalpost Chest Opener'
        'Hands-Behind-Head Chest Opener'
        'Eagle-Arm Chest Flow'
        'Bear-Hug Chest Stretch'
        'Dynamic Hug'
        'Serratus Punch'
        'Double Serratus Punch'
        'Push-Pull Chest Flow'
        'Boxing-Guard Chest Squeeze'
        'Jab-Cross Chest Rotation'
        'Hook Chest Rotation'
        'Double Palm Strike'
        'Karate Morote-Zuki'
        'Karate Yama-Zuki'
        'Wing Chun Double-Palm Press'
        'Wing Chun Chain-Punch Chest Rhythm'
        'Tai Chi Open and Close Hands'
        'Tai Chi Embrace Tiger Return to Mountain'
        'Tai Chi Play the Lute'
        'Tai Chi Cross Hands'
        'Tai Chi Ward Off'
        'Qigong Opening the Chest'
        'Qigong Separating the Clouds'
        'Qigong Holding the Ball'
        'Qigong Expanding the Sphere'
        'Qigong Pushing the Mountain'
        'Qigong Flying Wild Goose'
        'Qigong Crane Spreads Wings'
        'Eight Brocades Hold Up the Heavens'
        'Qigong Phoenix Opens Wings'
        'Eight Brocades Separate Heaven and Earth'
        'Five-Animals Crane Opens Wings'
        'Mountain-Pose Chest Lift'
        'Upward Salute'
        'Yoga Cactus Arms'
        'Yoga Reverse Prayer'
        'Yoga Eagle Arms'
        'Yoga Cow-Face Arms'
        'Warrior-I Chest Lift'
        'Warrior-II Chest Opening'
        'Reverse-Warrior Chest Opening'
        'Humble-Warrior Chest Opening'
        'Standing Yoga Backbend'
        'Extended Mountain Pose'
        'Standing Yoga Side Stretch'
        'Ballet First-Port Chest Carriage'
        'Ballet Second-Port Chest Opening'
        'Ballet Arabesque Chest Lift'
        'Flamenco Chest Lift'
        'Flamenco Chest Circle'
        'Belly-Dance Chest Pop'
        'Belly-Dance Chest Drop'
        'Belly-Dance Chest Slide'
        'Belly-Dance Chest Circle'
        'Belly-Dance Chest Figure Eight'
        'Odissi Ribcage Isolation'
        'Bharatanatyam Chest Lift'
        'Kathak Chest Turn'
        'Tango Frame Hold'
        'Ballroom Promenade Chest Rotation'
    )
    BACK = @(
        'Standing Spinal Flexion'
        'Standing Spinal Extension'
        'Standing Spinal Lateral Flexion'
        'Standing Spinal Rotation'
        'Standing Spinal Wave'
        'Standing Spine Roll'
        'Segmental Spinal Articulation'
        'Standing Thoracic Flexion'
        'Standing Thoracic Extension'
        'Standing Thoracic Rotation'
        'Standing Lumbar Flexion'
        'Standing Lumbar Extension'
        'Standing Lumbar Rotation'
        'Pelvic-Spine Wave'
        'Standing Body Roll'
        'Torso Circle'
        'Torso Figure Eight'
        'Standing Cat-Cow'
        'Standing Good Morning'
        'Standing Hip Hinge'
        'Single-Leg Hip Hinge'
        'B-Stance Good Morning'
        'Wide-Stance Hip Hinge'
        'Standing Side-Hinge Reach'
        'Standing Bow-and-Arrow Rotation'
        'Standing Bird Dog'
        'Standing Contralateral Reach'
        'Standing Diagonal Backline Reach'
        'Standing Swimmer'
        'Standing Backstroke'
        'Standing Reverse Fly'
        'Standing Scapular Squeeze'
        'Standing Lat Spread'
        'Standing Lat-Pulldown Arm Pattern'
        'Standing Straight-Arm Pulldown Pattern'
        'Standing Shadow Row'
        'Standing Shadow High Row'
        'Standing Shadow Low Row'
        'Standing One-Arm Shadow Row'
        'Standing Alternating Shadow Row'
        'Standing Superman'
        'Standing Locust Pose'
        'Standing Cobra Pose'
        'Standing Backbend'
        'Extended-Mountain Backline Stretch'
        'Standing Forward Fold'
        'Standing Half Forward Fold'
        'Pyramid Pose'
        'Wide-Legged Forward Fold'
        'Humble Warrior Pose'
        'Balancing Stick Pose'
        'Standing Bow Pose'
        'Airplane Pose'
        'Revolved Triangle Pose'
        'Revolved Side-Angle Pose'
        'Chair-Pose Twist'
        'Standing Yoga Twist'
        'Standing Yoga Side Bend'
        'Standing Banana Pose'
        'Standing Crescent-Moon Pose'
        'Tai Chi Bow-Stance Spine Coil'
        'Tai Chi Repulse-Monkey Torso Turn'
        'Tai Chi Brush-Knee Torso Turn'
        'Tai Chi Fan Through Back'
        'Tai Chi Needle at Sea Bottom'
        'Tai Chi White Snake Creeps Down'
        'Tai Chi Cloud-Hands Torso Turn'
        'Tai Chi Fair Lady Works Shuttles'
        'Tai Chi Rollback'
        'Qigong Spinal-Cord Breathing'
        'Qigong Swimming Dragon'
        'Qigong Back Shaking'
        'Qigong Waist Turning'
        'Qigong Rowing the Boat'
        'Qigong Scooping the Sea'
        'Eight Brocades Sway Head and Tail'
        'Eight Brocades Two Hands Hold the Feet'
        'Five-Animals Bear Sway'
        'Five-Animals Deer Turn'
        'Tai Chi Silk-Reeling Spine Coil'
        'Bagua Torso Coiling'
        'Xingyi Dragon Body'
        'Karate Hip-Spine Rotation'
        'Boxing Slip'
        'Boxing Roll'
        'Boxing Weave'
        'Boxing Pull-Counter Lean'
        'Capoeira Esquiva de Frente'
        'Capoeira Cocorinha'
        'Belly-Dance Body Wave'
        'Belly-Dance Reverse Body Wave'
        'Belly-Dance Torso Undulation'
        'Belly-Dance Ribcage Circle'
        'Ballet Cambre Back'
        'Ballet Cambre Side'
        'Ballet Cambre Forward'
        'Graham Contraction Standing'
        'Graham Release Standing'
        'Horton Flat Back'
        'Horton Lateral Stretch'
    )
    CORE = @(
        'Standing Abdominal Brace'
        'Standing Abdominal Hollowing'
        'Standing Pelvic Brace'
        'Standing Crunch'
        'Standing Side Crunch'
        'Standing Cross-Body Crunch'
        'Standing Knee-to-Elbow Crunch'
        'Opposite Knee-to-Elbow Crunch'
        'Same-Side Knee-to-Elbow Crunch'
        'Standing Bicycle Crunch'
        'Standing Oblique Crunch'
        'Standing Reverse Crunch'
        'Standing Knee Tuck'
        'Double-Hand Knee Drive'
        'Diagonal Knee Drive'
        'High-Knee Hold'
        'Single-Leg Brace Hold'
        'Single-Leg Core Balance'
        'Tandem-Stance Core Brace'
        'Braced March'
        'Standing Dead-Bug March'
        'Standing Sprinter Brace'
        'Standing Cross-Crawl Reach'
        'Standing Ipsilateral Reach'
        'Self-Resisted Anti-Rotation Press'
        'Self-Resisted Torso Rotation'
        'Self-Resisted Side Bend'
        'Self-Resisted Knee Lift'
        'Cross-Body Palm-to-Knee Press'
        'Same-Side Palm-to-Knee Press'
        'Overhead Brace Hold'
        'Front-Reach Brace'
        'Lateral-Reach Brace'
        'Diagonal-Reach Brace'
        'Around-the-World Arm Brace'
        'Standing Body-Line Lean'
        'Hip-Hinge Core Brace'
        'Squat Core Brace'
        'Lunge Core Brace'
        'Split-Stance Anti-Rotation Hold'
        'Unilateral-Reach Anti-Tilt Hold'
        'Offset-Arm March'
        'Overhead March'
        'Cross-Crawl March'
        'Standing Bear-Crawl Pattern'
        'Standing Mountain-Climber Pattern'
        'Skater Crunch Without Hop'
        'Standing Wood Chop'
        'Standing Reverse Wood Chop'
        'Standing Axe Chop'
        'Standing Canoe Twist'
        'Standing Kayak Twist'
        'Standing Russian Twist'
        'Standing Torso Rotation'
        'Braced Standing Hip Circle'
        'Braced Pelvic Clock'
        'Braced Pelvic Figure Eight'
        'Standing Side Bend'
        'Standing Windmill Reach'
        'Cross-Body Toe Reach'
        'Alternating Toe Reach'
        'Diagonal Hand-to-Knee Reach'
        'Elbow-to-Knee Isometric Hold'
        'Warrior-III Core Balance'
        'Tree-Pose Core Balance'
        'Eagle-Pose Core Balance'
        'Half-Moon Core Balance'
        'Dancer-Pose Core Balance'
        'Chair-Pose Core Hold'
        'Goddess-Pose Core Hold'
        'Warrior-II Core Hold'
        'Revolved Chair Pose'
        'Revolved Crescent Lunge'
        'One-Legged Mountain Pose'
        'Extended Hand-to-Big-Toe Pose'
        'Standing Pilates Spine Twist'
        'Upward-Salute Backline Brace'
        'Tai Chi Dantian Rotation'
        'Tai Chi Silk-Reeling Waist Turn'
        'Tai Chi Cloud-Hands Waist Turn'
        'Tai Chi Golden-Rooster Balance'
        'Tai Chi Kick Balance'
        'Bagua Circle-Walking Core Coil'
        'Xingyi Santi Stance'
        'Karate Sanchin Stance'
        'Karate Kiba-Dachi Brace'
        'Karate Zenkutsu-Dachi Brace'
        'Boxing Guard Brace'
        'Boxing Jab-Cross Rotation'
        'Boxing Hook Rotation'
        'Muay-Thai Knee Chamber'
        'Capoeira Ginga Core Flow'
        'Belly-Dance Abdominal Undulation'
        'Belly-Dance Hip-Figure-Eight Core Flow'
        'Salsa Cuban-Motion Core Flow'
        'Flamenco Core Brace'
        'Ballet Passe Core Balance'
        'Ballet Arabesque Core Balance'
        'Standing Pilates Hundred Arms'
        'Standing Pilates Roll-Down Brace'
    )
}
